### ISSUE TITLE
Refactor AddLoan

### ISSUE THREAD

**Issue by te4-henrik-stahl** [itggot-TE4/Yabs#443]
## ✨ Feature request
Use composition api instead 

### 📜 Acceptance Criteria
- [ ] AddLoad refactored
- [ ] Navbar refactored

### 💡 Additional context
Relate to #350

**Comment by itggot-linus-styren** [comment]
Notice, the original AddLoan component is broken, it was refactored to use vuetify in #173 but authors of that PR overlooked the meaning of b-popover component, it is not the same as v-tooltip. The closest to popover is the following: https://vuetifyjs.com/en/components/menus/

Suggestion is to callobrate with assignee for #422 and use v-menu instead of v-tooltip. This should also solve issues related to using composition API.
